<a href="https://colab.research.google.com/github/tjdux/pandas-for-finance/blob/main/01_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Series 만드는 방법

In [1]:
import pandas as pd

In [2]:
# Data Type: list
ls1= [1, 2, 3, 4, 5, 6, 7, 8, 9]
ls2 = [1, 2, 3, "Apple", "play", 6, 7, 8, 9]

sr1 = pd.Series(ls1)
sr1

sr2 = pd.Series(ls2)
sr2

0        1
1        2
2        3
3    Apple
4     play
5        6
6        7
7        8
8        9
dtype: object

In [3]:
# Series에 Name 설정
sr1.name = "Number"
sr2.name = "Word"
sr1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: Number, dtype: int64

In [4]:
# DataType: dictionary
dic1 = {"a": 1, "b": 2, "c": 3}
sr3 = pd.Series(dic1)
sr3.name = "Number"
sr3

a    1
b    2
c    3
Name: Number, dtype: int64

## CSV 파일을 Series로 불러오기

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
file_path = "/content/drive/MyDrive/financial pandas/삼성전자 종가.csv"
df = pd.read_csv(file_path, index_col=0, header=0)
samsung_price = df.squeeze(axis=1) # DataFrame -> Series
type(samsung_price)

pandas.core.series.Series

## Index & Value

In [7]:
samsung_price.index

Index(['2018-01-02', '2018-01-03', '2018-01-04', '2018-01-05', '2018-01-08',
       '2018-01-09', '2018-01-10', '2018-01-11', '2018-01-12', '2018-01-15',
       ...
       '2021-12-06', '2021-12-07', '2021-12-08', '2021-12-09', '2021-12-10',
       '2021-12-13', '2021-12-14', '2021-12-15', '2021-12-16', '2021-12-17'],
      dtype='object', name='Date', length=977)

In [8]:
# 2020-12-15 데이터가 있을까?
print('2020-12-15' in samsung_price.index)
print(samsung_price.loc['2020-12-15'])

True
73800

In [9]:
# 100번째 Data값?
print(samsung_price.iloc[100])

49500

## 새로운 값 추가

In [10]:
# samsung_price의 총 길이?
print(samsung_price.shape)
print(f"마지막 인덱스: {samsung_price.index[samsung_price.shape[0]-1]}")

(977,)
마지막 인덱스: 2021-12-17

In [11]:
# 2021-12-20 가격 업데이트
samsung_price.loc["2021-12-20"] = 77100
samsung_price.tail()

Date
2021-12-14    77000
2021-12-15    77600
2021-12-16    77800
2021-12-17    78000
2021-12-20    77100
Name: Close, dtype: int64

## 두 개의 Series 연결하기

In [19]:
file_path = "/content/drive/MyDrive/financial pandas/samsung_excel.xlsx"
series1_samsung = pd.read_excel(file_path, index_col=0, header=0,
                                sheet_name="Sheet1").squeeze()
series2_samsung = pd.read_excel(file_path, index_col=0, header=0,
                                sheet_name="Sheet2").squeeze()
series_samsung = pd.concat([series1_samsung, series2_samsung], ignore_index=False)
series_samsung

Date
2018-01-02    51020
2018-01-03    51620
2018-01-04    51080
2018-01-05    52120
2018-01-08    52020
              ...
2021-12-20    77100
2021-12-21    78100
2021-12-22    79400
2021-12-23    79900
2021-12-24    80500
Name: Close, Length: 982, dtype: int64

## 기본 통계치 구하기

In [21]:
print(f"고점: {samsung_price.max()}")
print(f"저점: {samsung_price.min()}")

고점: 91000
저점: 37450

In [22]:
samsung_price.describe()

count      978.000000
mean     57316.104294
std      14091.429092
min      37450.000000
25%      46300.000000
50%      51300.000000
75%      70200.000000
max      91000.000000
Name: Close, dtype: float64

In [27]:
# 고점인 날짜
print(f"{samsung_price.index[samsung_price.values == samsung_price.max()]}")
print(f"{samsung_price.index[samsung_price.argmax()]}")
print(f"{samsung_price.iloc[samsung_price.argmax()]}")

Index(['2021-01-11'], dtype='object', name='Date')
2021-01-11
91000